[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
NODE_ENV = "production"
GO_VERSION = "1.20"
TZ = "UTC"

[context.production.environment]
HUGO_VERSION = "0.112.7"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.112.7"
